config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/empty'
  get 'articles/index'
  get '/articles/:id/contenido', to: 'articles#contenido', as: 'contenido'
  get 'articles/empty'
  get 'articles/busqueda'
  get 'places/index'
  get 'places/empty'
  get 'restaurants/buscar_x_estado/muestra', to: 'restaurants#buscar_x_estado', as: 'muestra'
  get 'restaurants/buscar_x_tipo_comida/mostrar', to: 'restaurants#buscar_x_tipo_comida', as: 'mostrar'
  get 'restaurants/mapa'
  get 'restaurants/avanzada'
  get 'restaurants/buscar_x_tipo_promo/promo', to: 'restaurants#buscar_x_tipo_promo', as: 'promo'
  get 'home/index'
  get 'home/program_of_yumis'
  get 'home/quick_user_guide'
  get 'home/terms_of_use'
  get 'home/contact'
  get 'restaurants/calification-filter'
  get 'restaurants/buscador'

  root 'home#index'

  get 'reservations/index', to: 'reservations#index', as: :reservations_index
  get 'reservations/cancelar/:id', to: 'reservations#cancelar', as: :reservations_cancelar
  put 'reservations/cancelar/:id', to: 'reservations#actualizando_cancel', as: :actualizando_cancel

  namespace :administrador do
    get 'home', to: 'home#index'
    get '', to: 'home#index'
    resources :restaurants
    put 'approved/:id', to: 'restaurants#approve_restaurant', as: :approve
    get 'aprobados', to: 'restaurants#approved_restaurants', as: :aprobados
    get 'aprobados/:id', to: 'restaurants#cancel_restaurant', as: :cancel
    delete 'rechazar/:id', to: 'restaurants#reject_restaurant', as: :reject_restaurant
    get 'not_approved', to: 'restaurants#not_approved_restaurants', as: :not_approved
    resources :articles
    get '/articles/:id/confirm', to: 'articles#confirm', as: 'confirm'
    get :warning_diners, to: 'no_shows#warning_diners', as: :warning_diners
    get :should_block, to: 'no_shows#should_diner_block', as: :should_diners
    get 'should_block/:id', to: 'no_shows#block_diner', as: :block_diners
    get :blocked_diners, to: 'no_shows#blocked_diners', as: :blocked_diners
    get 'blocked_diners/:id', to: 'no_shows#unblock_diners', as: :unblock_diners
    get 'warning_diners/:id', to: 'no_shows#warn_diner', as: :warn_diners
    get :gift_diners, to: 'no_shows#gift_diner', as: :gift_diners
    get 'gift_diners/:id', to: 'no_shows#giving_yumis', as: :give_yumis
  end

  namespace :restaurante do
    get 'home', to: 'home#index'
    get 'editar', to: 'restaurants#edit'
    patch 'editar', to: 'restaurants#update', as: :restaurant
    put 'editar', to: 'restaurants#update', as: nil
    post 'borrar_photo', to: 'restaurants#destroy_photo'
    get 'display_reservations', to: 'reservations#display_reservations', as: 'reservas'
    get 'display_res_date', to: 'reservations#display_res_date', as: 'por_fecha'
    get 'show1', to: 'reservations#show1', as: 'show1'
    get 'show2', to: 'reservations#show2', as: 'show2'
    get 'cancelar-reservas', to: 'restaurants#reservation'
    get 'get-reservas', to: 'restaurants#get_reservation'
    patch 'cancelar-reserva', to: 'restaurants#cancel_reservation', as: :cancel_reserva
    resources :menu_types
    resources :promos
    resources :calendars
    resources :plates
    resources :reservations
    get '/reservations', to: 'reservations#index'
    put '/reservations/:id/update_status', to: 'reservations#update_status'
  end
  #Ruta para info de restaurante
  get 'restaurant_info/:restaurantID', to: 'restaurants#restaurant_info', as: :restaurant_info
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, skip: :registrations, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords' }
  devise_scope :user do
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: 'users/passwords#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get '/users/restaurant/sign_up', to: 'users/registrations#create_restaurant'
    post '/users/restaurant/sign_up', to: 'users/registrations#create'
    get 'usuario/editar', to: 'users/registrations#edit', as: :edit_user_registration
    put 'usuario/editar', to: 'users/registrations#update', as: nil
    patch 'usuario/editar', to: 'users/registrations#update', as: :user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/sign_up', to: 'users/registrations#new', as: :new_user_registration
    delete '/users', to: 'users/registrations#destroy', as: nil
    post '/users', to: 'users/registrations#create', as: nil
  end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurant, only: [:index, :show]
  get '/diner-subscriptions', to: 'diner_subscriptions#index'
  patch '/diner-subscriptions', to: 'diner_subscriptions#update'
  namespace 'api', defaults:{format:"json"} do
    namespace 'v1' do
      #Inicio Grupo 4 rutas
        devise_for :users
        #Lista de lugares
        get 'place_list', to: 'places#place_list'
        #Lista de restaurantes por estado
        get 'restaurant_list/:id', to: 'restaurants#restaurant_list'
        #LIsta de restaurantes por tipo de comida
        get 'restaurant_name', to: 'restaurants#restaurant_name'
        get 'restaurant_address', to: 'restaurants#restaurant_address'
        get 'restaurant_kitchen_type', to: 'restaurants#restaurant_kitchen_type'
        get 'restaurant_search/:id', to: 'restaurants#restaurant_search'
        #Lista de tipo de comida
        get 'kitchen_type_list', to:'kitchen_type#kitchen_type_list'
        get 'promo_type_list/:id', to:'promos#promo_type_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'
        get 'promo_restaurant/:id', to:'promos#promo_restaurant'
        get 'promo_dates_list/:id/:rest_id', to:'promos#promo_dates_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'

        post 'api_invitation', to:'api_invitation#api_invitation'
        post 'api_reservation', to:'api_invitation#api_reservation'
        get 'api_reservation/:id/1478965', to:'api_invitation#api_reserve_cancel'
        get 'api_reserve_invitation_yumies/:user_id/1478965', to:'api_invitation#api_reserve_invitation_yumies'
      #FIn Grupo 4 rutas
      # -------------------------------------------
      # Rutas de la seccion de preguntas frecuentes
      # -------------------------------------------
      get 'temas', to: 'articles#temas' # Retorna el listado de temas
      get 'articulos', to: 'articles#articulos' # Retorna el listado de articulos
      get 'art_per_tema/:id', to: 'articles#art_per_tema' # Retorna los articulos que pertenecen al tema especificado
      get 'add_tendencia/:id', to: 'articles#add_tendencia' # Aumenta la tendencia de un articulo al clickearlo
      # ------------------------------------------------
      # Rutas de la seccion de información de restaurant
      # ------------------------------------------------
      get 'restaurant_info/:id', to: 'restaurants#restaurant_info'# Retorna la info de un restaurant
      # ------------------------------------------
      # Rutas de la seccion de realizacion reserva
      # ------------------------------------------
      get 'reserva/:id', to: 'reservations#reserva' # Retorna las fechas del calendario junto a las promos
      # -------------------------------------------------
      # Ruta para retornar notificaciones de calificación
      # -------------------------------------------------
      get 'notificacion/calificacion_pend/:id', to: 'comments#pending_comment'
      get 'calificar/:id', to: 'comments#get_info'
      post 'calificar', to: 'comments#registrar_comment'
      post 'invitar_registro', to: 'invites#invitar'
    end
  end
  # Rutas para comensal
  namespace :comensal do
    get :editar, to: 'diners#edit'
    ## RUTAS PARA MIS YUMIS
    get :yumis, to: 'hist_yumis#mis_yumis'
    get :yumis_amigos, to: 'hist_yumis#yumis_amigos'
    get :yumis_reservas_efect, to: 'hist_yumis#yumis_reservas_efectuadas'
    get :yumis_reservas_noefect, to: 'hist_yumis#yumis_reservas_noefectuadas'
    get :yumis_reservas_canceladas, to: 'hist_yumis#yumis_reservas_canceladas'
    #####################################
    patch :editar, to: 'diners#update', as: :diner
    post :editar, to: 'diners#update', as: :diners
  end
  # rutas para obtener estado municipio y parroquia de lugar
  get 'get_estados', to: 'places#get_states'
  get 'get_municipios', to: 'places#get_municipios'
  get 'get_parroquias', to: 'places#get_parroquias'

  # Filtros para buscar restaurantes por calificaciones
  get 'restaurants-calification', to: 'restaurants#calification_filter'
  get 'buscador', to: 'restaurants#buscador'
  #bucar restaurantes por promociones activas
  # get 'restaurants-promos', to: 'restaurants#promos_date_filter'
  get 'restaurants-yummys', to: 'restaurants#yummys_filter'

  #Rutas para comentarios y Opiniones
  get 'ShowOpinion/:restaurantID', to: 'comments#ShowOpinion' , as: :my_link
  get 'my_comments', to: 'comments#my_comments'

  # rutas para crear los comentarios de las reservaciones
  get '/reservations/:id/comment', to: 'reservation_comment#new', as: 'reservation_comment'
  post '/reservations/:id/comment', to: 'reservation_comment#create'
  
  # ruta para crear reservas
  post '/reservation/:restID', to: 'reservations#create', as: :reservation_create

   #Post para invitar amigos a la reserva 
   post 'inviteF/:restID', to: 'invitations#create', as: :inviteF

end

app/controllers/restaurante/home_controller.rb
class Restaurante::HomeController < ApplicationController
  layout 'restaurante'
  before_action :authenticate_restaurant!
  def index; end
end

app/controllers/restaurante/menu_types_controller.rb
class Restaurante::MenuTypesController < ApplicationController
  before_action :set_menu_type, :set_plate, only: [:show, :edit, :update, :destroy]
  layout 'restaurante', only: %i[new create edit update index show]
  before_action :authenticate_user!

  # GET /menu_types
  # GET /menu_types.json
  def index
    #@menu_types = MenuType.all
    @menu_types = MenuType.all
    @plates = Plate.all
  end

  # GET /menu_types/1
  # GET /menu_types/1.json
  def show
    @menu_types = MenuType.includes(:plates).find(params[:id])
  end

  # GET /menu_types/new
  def new
    @menu_type = MenuType.new
    @plate = @menu_type.plates.build
  end

  # GET /menu_types/1/edit
  def edit
  end
  
  # POST /menu_types
  # POST /menu_types.json
  def create
    @menu_type = MenuType.new(menu_type_params)

    @restaurant = Restaurant.find_by user_id: current_user.id     #Se obtiene el ID del restaurante (usuario en sesion)
    @menu_type.restaurant_id = @restaurant.id 

    respond_to do |format|
      if @menu_type.save
        format.html { redirect_to [:restaurante, @menu_type], notice: 'Tipo de menú creado con éxito.' }
        format.json { render :show, status: :created, location: @menu_type }
      else
        format.html { render :new }
        format.json { render json: @menu_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_types/1
  # PATCH/PUT /menu_types/1.json
  def update
    respond_to do |format|
      if @menu_type.update(menu_type_params)
        format.html { redirect_to [:restaurante, @menu_type], notice: 'El menu ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @menu_type }
      else
        format.html { render :edit }
        format.json { render json: @menu_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_types/1
  # DELETE /menu_types/1.json
  def destroy
    @menu_type.destroy
    respond_to do |format|
      format.html { redirect_to restaurante_menu_types_url, notice: 'Tipo de menú eliminado con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_type                                                  #Busca por ID del tipo de menu antes de una accion
      @menu_type = MenuType.find(params[:id])
    end
    def set_plate                                             #Busca por ID del tipo de menu antes de una accion
      @plate = Plate.find_by_menu_type_id(params[:menu_type_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_type_params                                               #Define los parametros del tipo de menu
      params.require(:menu_type).permit(:name, :restaurant_id, plates_attributes: [:name, :description, :price])
    end
end

app/controllers/restaurante/plates_controller.rb
class Restaurante::PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]
  layout 'restaurante', only: %i[new create edit update index show]
  before_action :authenticate_user!

  # GET /plates
  # GET /plates.json
  def index
    @plates = Plate.all
    @plates = Plate.search(params[:term], params[:page])
  end

  # GET /plates/1
  # GET /plates/1.json
  def show
  end

  # GET /plates/new
  def new
    @plate = Plate.new
  end

  # GET /plates/1/edit
  def edit
  end

  # POST /plates
  # POST /plates.json
  def create
    @plate = Plate.new(plate_params)

    respond_to do |format|
      if @plate.save
        format.html { redirect_to [:restaurante, @plate], notice: 'El plato ha sido creado exitosamente.' }
        format.json { render :show, status: :created, location: @plate }
      else
        format.html { render :new }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plates/1
  # PATCH/PUT /plates/1.json
  def update
    respond_to do |format|
      if @plate.update(plate_params)
        format.html { redirect_to [:restaurante, @plate], notice: 'El plato ha sido modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @plate }
      else
        format.html { render :edit }
        format.json { render json: @plate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plates/1
  # DELETE /plates/1.json
  def destroy
    @plate.destroy
    respond_to do |format|
      format.html { redirect_to restaurante_plates_url, notice: 'El plato ha sido eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plate                                                                     #Busca por ID del plato antes de una accion
      @plate = Plate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plate_params                                                                   #Define los parametros del plato
      params.require(:plate).permit(:name, :description, :price, :menu_type_id)
    end
end

app/controllers/restaurante/reservations_controller.rb
class Restaurante::ReservationsController < ApplicationController
    include ApplicationHelper 
    layout 'restaurante'
    #before_action :authenticate_user!
    before_action :authenticate_user!, :check_for_restaurant_user, :set_restaurant
    skip_before_action :verify_authenticity_token


    def index
        @reservations = reservations_list()
    end

    def update_status
        reservation = Reservation.find(params[:id])
        reservation.status = params[:new_status].capitalize

        if (reservation.save)
            flash[:notice] = 'Se ha cambiado satisfactoriamente el status de la reserva'

            if (reservation.status == Reservation::USED)
                CommentRestaurantInviteMailer.with(reservation: reservation).send_invitation.deliver_now
            end
        else
            flash[:notice] = 'El status al que se intento cambiar la reserva es invalido'
        end

        redirect_to action: 'index'
    end

    
    #obtiene la lista de reservas que se han hecho en el restaurante
    def display_reservations 
        #@restaurantid = params[:restaurantid]
        #@dineridd = params[:dineridd]
        @reservaRest = Reservation.todas_rest(current_user.id)
    end

    def display_res_date 
        #
        
    end

    def show1 
        @search = params[:date]
        if @search 
            @reservaRestF = Reservation.todas_rest_f(current_user.id,params[:date])
            if @reservaRestF.empty? 
                @epa = flash[:warning] = "no se encontraron restaurantes en la fecha indicada"
            end
        end
    end

    def show2 
        #
    end

    private 
        def set_restaurant
            @restaurant =  Restaurant.find_by user_id: current_user.id  
        end
        
        def reservations_list
            @restaurant.reservations.order('reservation_date': :desc)
        end
    
end

app/views/shared/restaurante/_footer.html.erb
<footer class="main-footer">
    <strong>Copyright &copy; 2019 <a href="#">LaPromo</a>.</strong> Todos los derechos reservados
</footer>

app/views/shared/restaurante/_main_sidebar.html.erb
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <% if current_user.is_restaurant? && current_user.is_google %>
                    <%= image_tag(current_user.provider, class: 'img-circle') %>
                <% else %>
                    <%= image_tag('http://live.staticflickr.com/65535/49191292228_971e2c6fcb_m.jpg', class: 'img-circle') %>
                <% end %>

            </div>
            <div class="pull-left info">
                <p style="font-size: 13px"><%= current_user.restaurant.name %></p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
     
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Navegación</li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-edit"></i> <span>Mis Datos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="<%= 'active' if request.path == '/restaurante/editar'%>">
                        <%= link_to restaurante_editar_path do %>
                            <i class="fa fa-circle-o"></i> Datos Personales
                        <% end %>
                    </li>
                    <li class="<%= 'active' if request.path == '/usuario/editar'%>" >
                        <%= link_to  edit_user_registration_path do %>
                        <i class="fa fa-circle-o"></i> Datos de acceso
                        <% end %>
                    </li>
                </ul>
            </li>
            <li class="treeview">
                    <a href="#">
                        <i class="fa fa-pie-chart"></i> <span>Promociones</span>
                        <span class="pull-right-container">
                            <i class="fa fa-angle-left pull-right"></i>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="<%= 'active' if request.path == '/restaurante/promos'%>">
                            <%= link_to restaurante_promos_path do %>
                            <i class="fa fa-circle-o"></i>Promociones activas
                            <% end %>
                        </li>
                        <li class="<%= 'active' if request.path == '/restaurante/promos/new'%>">
                            <%= link_to new_restaurante_promo_path do %>
                            <i class="fa fa-circle-o"></i>Agregar promoción
                            <% end %>
                        </li>
                    </ul>
                </li>

            <li class="treeview <%= 'active' if request.path.include?('reserva')%>">
                <a href="#">
                    <i class="fa fa-calendar-minus-o"></i> <span>Reservas</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">

                    <li class="<%= 'active' if request.path == '/restaurante/display_reservations'  %>">
                        <%= link_to restaurante_reservas_path do %>
                            <i class="fa fa-circle-o"></i> Ver reservas
                        <% end %>
                    </li>
                    <li class="<%= 'active' if request.path == '/restaurante/display_res_date'  %>">
                        <%= link_to restaurante_por_fecha_path do %>
                            <i class="fa fa-circle-o"></i> En fecha determinada
                        <% end %>
                    </li>

                    <li class="<%= 'active' if request.path == '/restaurante/cancelar-reservas' || request.path.include?('get-reservas') %>" >
                        <%= link_to restaurante_cancelar_reservas_path do %>
                        <i class="fa fa-circle-o"></i> Cancelar reservas
                        <% end %>
                    </li>
                </ul>
            </li>


            <li>
                <a href="/restaurante/reservations">
                    <i class="fa fa-list-ul"></i> <span>Reservas</span>
                </a>
                
                <a href="/restaurante/menu_types">
                    <i class="fa fa-envelope"></i> <span>Menús</span>
                </a>
            </li>


            <li><a href="/restaurante/plates"><i class="fa fa-book"></i> <span>Platos</span></a></li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>