config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/empty'
  get 'articles/index'
  get '/articles/:id/contenido', to: 'articles#contenido', as: 'contenido'
  get 'articles/empty'
  get 'articles/busqueda'
  get 'places/index'
  get 'places/empty'
  get 'restaurants/buscar_x_estado/muestra', to: 'restaurants#buscar_x_estado', as: 'muestra'
  get 'restaurants/buscar_x_tipo_comida/mostrar', to: 'restaurants#buscar_x_tipo_comida', as: 'mostrar'
  get 'restaurants/mapa'
  get 'restaurants/avanzada'
  get 'restaurants/buscar_x_tipo_promo/promo', to: 'restaurants#buscar_x_tipo_promo', as: 'promo'
  get 'home/index'
  get 'home/program_of_yumis'
  get 'home/quick_user_guide'
  get 'home/terms_of_use'
  get 'home/contact'
  get 'restaurants/calification-filter'
  get 'restaurants/buscador'

  root 'home#index'

  get 'reservations/index', to: 'reservations#index', as: :reservations_index
  get 'reservations/cancelar/:id', to: 'reservations#cancelar', as: :reservations_cancelar
  put 'reservations/cancelar/:id', to: 'reservations#actualizando_cancel', as: :actualizando_cancel

  namespace :administrador do
    get 'home', to: 'home#index'
    get '', to: 'home#index'
    resources :restaurants
    put 'approved/:id', to: 'restaurants#approve_restaurant', as: :approve
    get 'aprobados', to: 'restaurants#approved_restaurants', as: :aprobados
    get 'aprobados/:id', to: 'restaurants#cancel_restaurant', as: :cancel
    delete 'rechazar/:id', to: 'restaurants#reject_restaurant', as: :reject_restaurant
    get 'not_approved', to: 'restaurants#not_approved_restaurants', as: :not_approved
    resources :articles
    get '/articles/:id/confirm', to: 'articles#confirm', as: 'confirm'
    get :warning_diners, to: 'no_shows#warning_diners', as: :warning_diners
    get :should_block, to: 'no_shows#should_diner_block', as: :should_diners
    get 'should_block/:id', to: 'no_shows#block_diner', as: :block_diners
    get :blocked_diners, to: 'no_shows#blocked_diners', as: :blocked_diners
    get 'blocked_diners/:id', to: 'no_shows#unblock_diners', as: :unblock_diners
    get 'warning_diners/:id', to: 'no_shows#warn_diner', as: :warn_diners
    get :gift_diners, to: 'no_shows#gift_diner', as: :gift_diners
    get 'gift_diners/:id', to: 'no_shows#giving_yumis', as: :give_yumis
  end

  namespace :restaurante do
    get 'home', to: 'home#index'
    get 'editar', to: 'restaurants#edit'
    patch 'editar', to: 'restaurants#update', as: :restaurant
    put 'editar', to: 'restaurants#update', as: nil
    post 'borrar_photo', to: 'restaurants#destroy_photo'
    get 'display_reservations', to: 'reservations#display_reservations', as: 'reservas'
    get 'display_res_date', to: 'reservations#display_res_date', as: 'por_fecha'
    get 'show1', to: 'reservations#show1', as: 'show1'
    get 'show2', to: 'reservations#show2', as: 'show2'
    get 'cancelar-reservas', to: 'restaurants#reservation'
    get 'get-reservas', to: 'restaurants#get_reservation'
    patch 'cancelar-reserva', to: 'restaurants#cancel_reservation', as: :cancel_reserva
    resources :menu_types
    resources :promos
    resources :calendars
    resources :plates
    resources :reservations
    get '/reservations', to: 'reservations#index'
    put '/reservations/:id/update_status', to: 'reservations#update_status'
  end
  #Ruta para info de restaurante
  get 'restaurant_info/:restaurantID', to: 'restaurants#restaurant_info', as: :restaurant_info
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, skip: :registrations, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords' }
  devise_scope :user do
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: 'users/passwords#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get '/users/restaurant/sign_up', to: 'users/registrations#create_restaurant'
    post '/users/restaurant/sign_up', to: 'users/registrations#create'
    get 'usuario/editar', to: 'users/registrations#edit', as: :edit_user_registration
    put 'usuario/editar', to: 'users/registrations#update', as: nil
    patch 'usuario/editar', to: 'users/registrations#update', as: :user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/sign_up', to: 'users/registrations#new', as: :new_user_registration
    delete '/users', to: 'users/registrations#destroy', as: nil
    post '/users', to: 'users/registrations#create', as: nil
  end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurant, only: [:index, :show]
  get '/diner-subscriptions', to: 'diner_subscriptions#index'
  patch '/diner-subscriptions', to: 'diner_subscriptions#update'
  namespace 'api', defaults:{format:"json"} do
    namespace 'v1' do
      #Inicio Grupo 4 rutas
        devise_for :users
        #Lista de lugares
        get 'place_list', to: 'places#place_list'
        #Lista de restaurantes por estado
        get 'restaurant_list/:id', to: 'restaurants#restaurant_list'
        #LIsta de restaurantes por tipo de comida
        get 'restaurant_name', to: 'restaurants#restaurant_name'
        get 'restaurant_address', to: 'restaurants#restaurant_address'
        get 'restaurant_kitchen_type', to: 'restaurants#restaurant_kitchen_type'
        get 'restaurant_search/:id', to: 'restaurants#restaurant_search'
        #Lista de tipo de comida
        get 'kitchen_type_list', to:'kitchen_type#kitchen_type_list'
        get 'promo_type_list/:id', to:'promos#promo_type_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'
        get 'promo_restaurant/:id', to:'promos#promo_restaurant'
        get 'promo_dates_list/:id/:rest_id', to:'promos#promo_dates_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'

        post 'api_invitation', to:'api_invitation#api_invitation'
        post 'api_reservation', to:'api_invitation#api_reservation'
        get 'api_reservation/:id/1478965', to:'api_invitation#api_reserve_cancel'
        get 'api_reserve_invitation_yumies/:user_id/1478965', to:'api_invitation#api_reserve_invitation_yumies'
      #FIn Grupo 4 rutas
      # -------------------------------------------
      # Rutas de la seccion de preguntas frecuentes
      # -------------------------------------------
      get 'temas', to: 'articles#temas' # Retorna el listado de temas
      get 'articulos', to: 'articles#articulos' # Retorna el listado de articulos
      get 'art_per_tema/:id', to: 'articles#art_per_tema' # Retorna los articulos que pertenecen al tema especificado
      get 'add_tendencia/:id', to: 'articles#add_tendencia' # Aumenta la tendencia de un articulo al clickearlo
      # ------------------------------------------------
      # Rutas de la seccion de información de restaurant
      # ------------------------------------------------
      get 'restaurant_info/:id', to: 'restaurants#restaurant_info'# Retorna la info de un restaurant
      # ------------------------------------------
      # Rutas de la seccion de realizacion reserva
      # ------------------------------------------
      get 'reserva/:id', to: 'reservations#reserva' # Retorna las fechas del calendario junto a las promos
      # -------------------------------------------------
      # Ruta para retornar notificaciones de calificación
      # -------------------------------------------------
      get 'notificacion/calificacion_pend/:id', to: 'comments#pending_comment'
      get 'calificar/:id', to: 'comments#get_info'
      post 'calificar', to: 'comments#registrar_comment'
      post 'invitar_registro', to: 'invites#invitar'
    end
  end
  # Rutas para comensal
  namespace :comensal do
    get :editar, to: 'diners#edit'
    ## RUTAS PARA MIS YUMIS
    get :yumis, to: 'hist_yumis#mis_yumis'
    get :yumis_amigos, to: 'hist_yumis#yumis_amigos'
    get :yumis_reservas_efect, to: 'hist_yumis#yumis_reservas_efectuadas'
    get :yumis_reservas_noefect, to: 'hist_yumis#yumis_reservas_noefectuadas'
    get :yumis_reservas_canceladas, to: 'hist_yumis#yumis_reservas_canceladas'
    #####################################
    patch :editar, to: 'diners#update', as: :diner
    post :editar, to: 'diners#update', as: :diners
  end
  # rutas para obtener estado municipio y parroquia de lugar
  get 'get_estados', to: 'places#get_states'
  get 'get_municipios', to: 'places#get_municipios'
  get 'get_parroquias', to: 'places#get_parroquias'

  # Filtros para buscar restaurantes por calificaciones
  get 'restaurants-calification', to: 'restaurants#calification_filter'
  get 'buscador', to: 'restaurants#buscador'
  #bucar restaurantes por promociones activas
  # get 'restaurants-promos', to: 'restaurants#promos_date_filter'
  get 'restaurants-yummys', to: 'restaurants#yummys_filter'

  #Rutas para comentarios y Opiniones
  get 'ShowOpinion/:restaurantID', to: 'comments#ShowOpinion' , as: :my_link
  get 'my_comments', to: 'comments#my_comments'

  # rutas para crear los comentarios de las reservaciones
  get '/reservations/:id/comment', to: 'reservation_comment#new', as: 'reservation_comment'
  post '/reservations/:id/comment', to: 'reservation_comment#create'
  
  # ruta para crear reservas
  post '/reservation/:restID', to: 'reservations#create', as: :reservation_create

   #Post para invitar amigos a la reserva 
   post 'inviteF/:restID', to: 'invitations#create', as: :inviteF

end

app/controllers/administrador/articles_controller.rb
class Administrador::ArticlesController < ApplicationController
layout 'administrador'
helper_method :sort_column, :sort_direction
before_action :set_article, only: [:show, :edit, :update, :destroy, :confirm]

  # GET 
  def index
    @search = params[:title]
    @cont = 0 
    @SC_title = 0
    @SC_description = 0
    @SC_tendencia = 0
    @SC_usuario = 0
    @SC_tema = 0
    @ASC0_DESC1 = 0
    if @search
      @articles = Article.where('title ILIKE ?',"%#{params[:title]}%").page(params[:page]).per_page(10).order(sort_column+" "+sort_direction)
      @cont = 1
    else
      @articles = Article.all.page(params[:page]).per_page(10).order(sort_column+" "+sort_direction)
      case sort_column
      when "title"
        if sort_direction == "asc"
          @SC_title = 1
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 1
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 1
        end
      when "description"
        if sort_direction == "asc"
          @SC_title = 0
          @SC_description = 1
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 0
          @SC_description = 1
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 1
        end
      when "cont_trend"
        if sort_direction == "asc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 1
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 1
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 1
        end
      when "cont_trend"
        if sort_direction == "asc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 1
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 1
          @SC_usuario = 0
          @SC_tema = 0
          @ASC0_DESC1 = 1
        end
      when "user_id"
        if sort_direction == "asc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 1
          @SC_tema = 0
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 1
          @SC_tema = 0
          @ASC0_DESC1 = 1
        end
      when "topic_id"
        if sort_direction == "asc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 1
          @ASC0_DESC1 = 0
        elsif sort_direction == "desc"
          @SC_title = 0
          @SC_description = 0
          @SC_tendencia = 0
          @SC_usuario = 0
          @SC_tema = 1
          @ASC0_DESC1 = 1
        end
      end #DEL CASE
    end #DEL IF @articles
  end #DEL DEF

  # GET 
  def show
    @article = Article.find(params[:id])
  end

  # GET 
  def confirm
    #Manejo de sql (modelo) para obtener boolean
    if @article.destroy
      render json: {message: "Articulo " + params[:name] + " fue eliminado satisfactoriamente"}, status: :ok
    else
      render json: {message: "No se pudo realizar el delete del articulo " + params[:name] + ". Por favor verificar el articulo"}, status: :internal_server_error
    end
  end

  # GET 
  def new
    @article = Article.new()

    #@topics = Topic.all
  end
  # POST 
  def create
    @article = Article.new(article_params)
    @article.cont_trend = 0
    @article.user_id = current_user.id
      if @article.save
       redirect_to administrador_articles_path, 
          notice: 'El artículo fue creado exitosamente.'
      else
        render :new 
      end

  end

  # GET 
  def edit
    @article = Article.find(params[:id])
  end

  # PATCH/PUT 
  def update
      if @article.update(article_params)
        redirect_to administrador_articles_path, 
          notice: 'El artículo fue modificado exitosamente.'
      else
        render :edit 
      end
    
  end

  def sort_column
      params[:sort] || "title"
    end

  def sort_direction
      params[:direction] || "asc"
    end
  # DELETE 
  def destroy
    @article.destroy
    redirect_to administrador_articles_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description, :cont_trend, :user_id, :topic_id)
    end

end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController

    # Retorna los temas
    def temas
        @topics = Topic.all.order('name ASC')
        @errors = {
            description: 'No error',
        }
        if @topics.empty?
            @errors[:disponibilidad] = "No se consiguieron preguntas frecuentes de este tema."
            flash[:description] = @errors[:disponibilidad]
        end
    end

    # Retorna los articulos
    def articulos
        @articles = Article.all.order('title ASC')
        @errors = {
            description: 'No error',
        }
        if @articles.empty?
            @errors[:disponibilidad] = "Actualmente no se tiene preguntas registradas."
            flash[:description] = @errors[:disponibilidad]
        end
    end

    # Retorna los articulos de un tema
    def art_per_tema
        @topic = Topic.find(params[:id])
        @topic.cont_trend = @topic.cont_trend + 1
        @topic.save
        @articles = Article.joins(:topic).where(:topics => { :id => params[:id] }).all
        @errors = {
            description: 'No error',
        }
        if @articles.empty?
            @errors[:disponibilidad] = "No se consiguieron articulos de este tema."
            flash[:description] = @errors[:disponibilidad]
        end
    end

    # Aumenta la tendencia de un articulo
    def add_tendencia
        @article = Article.find(params[:id])
        @article.cont_trend = @article.cont_trend + 1
        @article.save      
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @topics = Topic.find(params[:topic_id])
        cont_trend = @topics.cont_trend + 1
        @topics.update("cont_trend" => cont_trend)
        @articles = Article.where(topic_id: params[:topic_id]).page(params[:page]).per_page(8)

        if @articles.empty?
            flash[:warning] = "Actualmente no existen preguntas frecuentes registradas"
        else
            flash[:warning] = "Se han encontrado preguntas frecuentes"
        end
    end

    def contenido
        @articles = Article.find(params[:id])
        cont_trend = @articles.cont_trend + 1
        @articles.update("cont_trend" => cont_trend)
        @tendencia = Article.order(cont_trend: :desc).limit(5)
        flash[:warning] = "Se encontro la pregunta frecuente"

    end

    def busqueda
        @search = params[:title]
        if @search
            @articles = Article.where('title ILIKE ? or description ILIKE ?',"%#{params[:title]}%","%#{params[:title]}%").page(params[:page]).per_page(8)
            flash[:warning] = "Se encontraron resultados"
            if @articles.empty?
                flash[:warning] = "La busqueda no devolvio resultados"
                render :empty, busqueda: @search
            end
        end
    end

    def empty
        @search = params([:busqueda])
    end

    private

    def article_params
        params.require(:article).permit(:title, :description, :cont_trend, :user_id, :topic_id)
    end

end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/busqueda.html.erb
<body>
    <div id="wrapper">


        <div class="content2">
           
                <div class="text-center">
                    <i class="fas fa-comments" style="font-size: 3em; color:darkgray"></i>
                    <br><br>

                    <h3 class="mb-3 orange">Resultado de la búsqueda</h3>
                    <p class="text-muted"> Si no logras encontrar la pregunta que estabas buscando<br/> Envíanos tus preguntas por e-mail y las responderemos a la brevedad posible!<br>
                   
                    </p>      
                        <%= mail_to 'lapromoucab@gmail.com' do%>
                                    <button type="button" class="btn btn-success waves-effect waves-light mt-2 mr-1" ><i class="fas fa-envelope"></i> Envía un e-mail</button><%end%>
               
                </div>
               
           


       
                 <div class="subcont">
                    <div class="row pt-5">
                        <% @articles.each do |article|%>
                        <div class="col-lg-5 offset-lg-1">
                            <!-- Question/Answer -->
                            
                                <div>
                                    <div class="faq-question-q-box">Q.</div>
                                    <h4 class="faq-question" style="color: black;" data-wow-delay=".1s"><%= link_to article.title, contenido_path(article.id), :style => "color: black;" %></h4></a>
                                    <p class="faq-answer mb-4" style="font-size: 10px;"> Cantidad de visitas: <%= article.cont_trend %></p>
                                    
                                </div>

                                              
    
                        </div> <!--/col-lg-5 -->                       
                        <%end%>  

                    </div> <!--/row pt-5 -->
                         
                    <%= will_paginate @articles, class: 'digg_pagination justify-content-center', style:'float:right; position: relative; left:-50%;', previous_label:"<", next_label:">"%> 
                    <br>
                    <br>
                    <button type="submit" style="background-color: #b4b2b2; color:black; border-color: #b4b2b2" class="btn btn-info btn-flat float-left" onClick="history.back()">Volver</button>
                </div> <!--/subcont -->

        </div> <!-- content -->

    </div> <!-- wrapper --> 
 
</body>

app/views/articles/contenido.html.erb
<body>
    <div id="wrapper">


        <div class="content2">
                <div class="text-center">
                    <i class="fas fa-comments" style="font-size: 3em; color:darkgray"></i>
                    <br><br>

                    <h3 class="mb-3 orange"><%= @articles.title %></h3>
                    <p class="text-muted"> Si no logras encontrar la pregunta que estabas buscando<br/> Envíanos tus preguntas por e-mail y las responderemos a la brevedad posible!</p>
                    <%= mail_to 'lapromoucab@gmail.com' do%>
                                    <button type="button" class="btn btn-success waves-effect waves-light mt-2 mr-1" ><i class="fas fa-envelope"></i> Envía un e-mail</button><%end%>
                </div>
                <br>
                <div class="subcont">
                        <div class="row pt-5">
                            <div class="col-lg-6 offset-lg-1">
                                <p style="text-align: justify;">
                                    <%= @articles.description %>
                                </p>
                            </div>
                            <!--/col-md-5 -->
                        
                        <div class="col-lg-5">
                                <h4 class="mb-3" style="margin-left:35px; color: #e09b23; ">Articulos Tendencia</h4>
                                    <ul style="list-style-type:circle;">
                                        <% @tendencia.each do |tend| %>
                                        <li class="mb-3" ><%= link_to tend.title, contenido_path(tend.id), :style => "color: gray;" %> </li>
                                        <% end %>
                                    </ul>
                                 
        
                            </div>
                            <!--/col-md-5-->
                        </div><!--/row pt-5 -->
                        <br>
                        <br>
                        <div class="box-footer clearfix row">
                            <div class="col-sm-2">
                            <button type="submit" style="background-color: #b4b2b2; color:black; border-color: #b4b2b2" class="btn btn-info btn-flat float-left" onClick="history.back()">Volver</button>
                            </div>
                            <div class="col-sm-6 text-center">
                              <a href="../../topics/index" class="btn btn-info waves-effect waves-light" data-animation="fadein"
                               data-plugin="custommodal" data-overlaycolor="#e09b23">Volver a temas</a>
                            </div>
                        </div>
        </div> <!-- content -->

    </div> <!-- wrapper --> 
      
</body>

app/views/articles/empty.html.erb
    <head>
        <title>ERROR</title>
    </head>

    <body>

        <!-- Begin page -->
        <div id="wrapper">
            <div class="content2">
                      
                                <div class="text-center">
                                    <i class="h1 far fa-frown text-muted"></i> <i class=""></i>
                                    <h1 class="mb-3 orange" style ="color: #e09b23">No se obtuvieron resultados para "<%=@search%>"</h1>
                                    <p class="text-muted"> Lo sentimos, no se encontraron  preguntas frecuentes registradas en nuestro sistema bajo su criterio de búsqueda.<br>
                                    Envíenos sus preguntas por e-mail y las responderemos a la brevedad posible<br><br></p>

                                    <%= mail_to 'lapromoucab@gmail.com' do%>
                                    <button type="button" class="btn btn-success waves-effect waves-light mt-2 mr-1" ><i class="fas fa-envelope"></i> Envía un e-mail</button><%end%>
                                    <button type="submit" style="background-color: #b4b2b2; color:black; border-color: #b4b2b2" class="btn btn-info btn-flat waves-effect waves-light mt-2 mr-1" onClick="history.back()">Volver</button>

                                </div>
                            </div>
        </div>
        
    </body>



 

     

app/views/articles/index.html.erb
<body>
    <div id="wrapper">


        <div class="content2">
           
                <div class="text-center">
                    <i class="fas fa-comments" style="font-size: 3em; color:darkgray"></i>
                    <br><br>

                    <h3 class="mb-3 orange"><%= @topics.name %></h3>
                    <p class="text-muted"> Si no logras encontrar la pregunta que estabas buscando<br/> Envíanos tus preguntas por e-mail y las responderemos a la brevedad posible!<br>
                    Cantidad de visitas: <%=@topics.cont_trend%>
                    </p>      
                       <%= mail_to 'lapromoucab@gmail.com' do%>
                                    <button type="button" class="btn btn-success waves-effect waves-light mt-2 mr-1" ><i class="fas fa-envelope"></i> Envía un e-mail</button><%end%>
               
                </div>
               
           


       
                 <div class="subcont">
                    <div class="row pt-5">
                        <% @articles.each do |article|%>
                        <div class="col-lg-5 offset-lg-1">
                            <!-- Question/Answer -->
                            
                                <div>
                                    <div class="faq-question-q-box">Q.</div>
                                    <h4 class="faq-question" style="color: black;" data-wow-delay=".1s"><%= link_to article.title, contenido_path(article.id), :style => "color: black;" %></h4></a>
                                    <p class="faq-answer mb-4" style="font-size: 10px;"> Cantidad de visitas: <%= article.cont_trend %></p>
                                    
                                </div>

                                              
    
                        </div> <!--/col-lg-5 -->                       
                        <%end%>  

                    </div> <!--/row pt-5 -->
                         
                    <%= will_paginate @articles, class: 'digg_pagination justify-content-center', style:'float:right; position: relative; left:-50%;', previous_label:"<", next_label:">"%> 
                    <br>
                    <br>
                    <button type="submit" style="background-color: #b4b2b2; color:black; border-color: #b4b2b2" class="btn btn-info btn-flat float-left" onClick="history.back()">Volver</button>
                </div> <!--/subcont -->

        </div> <!-- content -->

    </div> <!-- wrapper --> 
 
</body>