config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/empty'
  get 'articles/index'
  get '/articles/:id/contenido', to: 'articles#contenido', as: 'contenido'
  get 'articles/empty'
  get 'articles/busqueda'
  get 'places/index'
  get 'places/empty'
  get 'restaurants/buscar_x_estado/muestra', to: 'restaurants#buscar_x_estado', as: 'muestra'
  get 'restaurants/buscar_x_tipo_comida/mostrar', to: 'restaurants#buscar_x_tipo_comida', as: 'mostrar'
  get 'restaurants/mapa'
  get 'restaurants/avanzada'
  get 'restaurants/buscar_x_tipo_promo/promo', to: 'restaurants#buscar_x_tipo_promo', as: 'promo'
  get 'home/index'
  get 'home/program_of_yumis'
  get 'home/quick_user_guide'
  get 'home/terms_of_use'
  get 'home/contact'
  get 'restaurants/calification-filter'
  get 'restaurants/buscador'

  root 'home#index'

  get 'reservations/index', to: 'reservations#index', as: :reservations_index
  get 'reservations/cancelar/:id', to: 'reservations#cancelar', as: :reservations_cancelar
  put 'reservations/cancelar/:id', to: 'reservations#actualizando_cancel', as: :actualizando_cancel

  namespace :administrador do
    get 'home', to: 'home#index'
    get '', to: 'home#index'
    resources :restaurants
    put 'approved/:id', to: 'restaurants#approve_restaurant', as: :approve
    get 'aprobados', to: 'restaurants#approved_restaurants', as: :aprobados
    get 'aprobados/:id', to: 'restaurants#cancel_restaurant', as: :cancel
    delete 'rechazar/:id', to: 'restaurants#reject_restaurant', as: :reject_restaurant
    get 'not_approved', to: 'restaurants#not_approved_restaurants', as: :not_approved
    resources :articles
    get '/articles/:id/confirm', to: 'articles#confirm', as: 'confirm'
    get :warning_diners, to: 'no_shows#warning_diners', as: :warning_diners
    get :should_block, to: 'no_shows#should_diner_block', as: :should_diners
    get 'should_block/:id', to: 'no_shows#block_diner', as: :block_diners
    get :blocked_diners, to: 'no_shows#blocked_diners', as: :blocked_diners
    get 'blocked_diners/:id', to: 'no_shows#unblock_diners', as: :unblock_diners
    get 'warning_diners/:id', to: 'no_shows#warn_diner', as: :warn_diners
    get :gift_diners, to: 'no_shows#gift_diner', as: :gift_diners
    get 'gift_diners/:id', to: 'no_shows#giving_yumis', as: :give_yumis
  end

  namespace :restaurante do
    get 'home', to: 'home#index'
    get 'editar', to: 'restaurants#edit'
    patch 'editar', to: 'restaurants#update', as: :restaurant
    put 'editar', to: 'restaurants#update', as: nil
    post 'borrar_photo', to: 'restaurants#destroy_photo'
    get 'display_reservations', to: 'reservations#display_reservations', as: 'reservas'
    get 'display_res_date', to: 'reservations#display_res_date', as: 'por_fecha'
    get 'show1', to: 'reservations#show1', as: 'show1'
    get 'show2', to: 'reservations#show2', as: 'show2'
    get 'cancelar-reservas', to: 'restaurants#reservation'
    get 'get-reservas', to: 'restaurants#get_reservation'
    patch 'cancelar-reserva', to: 'restaurants#cancel_reservation', as: :cancel_reserva
    resources :menu_types
    resources :promos
    resources :calendars
    resources :plates
    resources :reservations
    get '/reservations', to: 'reservations#index'
    put '/reservations/:id/update_status', to: 'reservations#update_status'
  end
  #Ruta para info de restaurante
  get 'restaurant_info/:restaurantID', to: 'restaurants#restaurant_info', as: :restaurant_info
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, skip: :registrations, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords' }
  devise_scope :user do
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: 'users/passwords#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get '/users/restaurant/sign_up', to: 'users/registrations#create_restaurant'
    post '/users/restaurant/sign_up', to: 'users/registrations#create'
    get 'usuario/editar', to: 'users/registrations#edit', as: :edit_user_registration
    put 'usuario/editar', to: 'users/registrations#update', as: nil
    patch 'usuario/editar', to: 'users/registrations#update', as: :user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/sign_up', to: 'users/registrations#new', as: :new_user_registration
    delete '/users', to: 'users/registrations#destroy', as: nil
    post '/users', to: 'users/registrations#create', as: nil
  end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurant, only: [:index, :show]
  get '/diner-subscriptions', to: 'diner_subscriptions#index'
  patch '/diner-subscriptions', to: 'diner_subscriptions#update'
  namespace 'api', defaults:{format:"json"} do
    namespace 'v1' do
      #Inicio Grupo 4 rutas
        devise_for :users
        #Lista de lugares
        get 'place_list', to: 'places#place_list'
        #Lista de restaurantes por estado
        get 'restaurant_list/:id', to: 'restaurants#restaurant_list'
        #LIsta de restaurantes por tipo de comida
        get 'restaurant_name', to: 'restaurants#restaurant_name'
        get 'restaurant_address', to: 'restaurants#restaurant_address'
        get 'restaurant_kitchen_type', to: 'restaurants#restaurant_kitchen_type'
        get 'restaurant_search/:id', to: 'restaurants#restaurant_search'
        #Lista de tipo de comida
        get 'kitchen_type_list', to:'kitchen_type#kitchen_type_list'
        get 'promo_type_list/:id', to:'promos#promo_type_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'
        get 'promo_restaurant/:id', to:'promos#promo_restaurant'
        get 'promo_dates_list/:id/:rest_id', to:'promos#promo_dates_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'

        post 'api_invitation', to:'api_invitation#api_invitation'
        post 'api_reservation', to:'api_invitation#api_reservation'
        get 'api_reservation/:id/1478965', to:'api_invitation#api_reserve_cancel'
        get 'api_reserve_invitation_yumies/:user_id/1478965', to:'api_invitation#api_reserve_invitation_yumies'
      #FIn Grupo 4 rutas
      # -------------------------------------------
      # Rutas de la seccion de preguntas frecuentes
      # -------------------------------------------
      get 'temas', to: 'articles#temas' # Retorna el listado de temas
      get 'articulos', to: 'articles#articulos' # Retorna el listado de articulos
      get 'art_per_tema/:id', to: 'articles#art_per_tema' # Retorna los articulos que pertenecen al tema especificado
      get 'add_tendencia/:id', to: 'articles#add_tendencia' # Aumenta la tendencia de un articulo al clickearlo
      # ------------------------------------------------
      # Rutas de la seccion de información de restaurant
      # ------------------------------------------------
      get 'restaurant_info/:id', to: 'restaurants#restaurant_info'# Retorna la info de un restaurant
      # ------------------------------------------
      # Rutas de la seccion de realizacion reserva
      # ------------------------------------------
      get 'reserva/:id', to: 'reservations#reserva' # Retorna las fechas del calendario junto a las promos
      # -------------------------------------------------
      # Ruta para retornar notificaciones de calificación
      # -------------------------------------------------
      get 'notificacion/calificacion_pend/:id', to: 'comments#pending_comment'
      get 'calificar/:id', to: 'comments#get_info'
      post 'calificar', to: 'comments#registrar_comment'
      post 'invitar_registro', to: 'invites#invitar'
    end
  end
  # Rutas para comensal
  namespace :comensal do
    get :editar, to: 'diners#edit'
    ## RUTAS PARA MIS YUMIS
    get :yumis, to: 'hist_yumis#mis_yumis'
    get :yumis_amigos, to: 'hist_yumis#yumis_amigos'
    get :yumis_reservas_efect, to: 'hist_yumis#yumis_reservas_efectuadas'
    get :yumis_reservas_noefect, to: 'hist_yumis#yumis_reservas_noefectuadas'
    get :yumis_reservas_canceladas, to: 'hist_yumis#yumis_reservas_canceladas'
    #####################################
    patch :editar, to: 'diners#update', as: :diner
    post :editar, to: 'diners#update', as: :diners
  end
  # rutas para obtener estado municipio y parroquia de lugar
  get 'get_estados', to: 'places#get_states'
  get 'get_municipios', to: 'places#get_municipios'
  get 'get_parroquias', to: 'places#get_parroquias'

  # Filtros para buscar restaurantes por calificaciones
  get 'restaurants-calification', to: 'restaurants#calification_filter'
  get 'buscador', to: 'restaurants#buscador'
  #bucar restaurantes por promociones activas
  # get 'restaurants-promos', to: 'restaurants#promos_date_filter'
  get 'restaurants-yummys', to: 'restaurants#yummys_filter'

  #Rutas para comentarios y Opiniones
  get 'ShowOpinion/:restaurantID', to: 'comments#ShowOpinion' , as: :my_link
  get 'my_comments', to: 'comments#my_comments'

  # rutas para crear los comentarios de las reservaciones
  get '/reservations/:id/comment', to: 'reservation_comment#new', as: 'reservation_comment'
  post '/reservations/:id/comment', to: 'reservation_comment#create'
  
  # ruta para crear reservas
  post '/reservation/:restID', to: 'reservations#create', as: :reservation_create

   #Post para invitar amigos a la reserva 
   post 'inviteF/:restID', to: 'invitations#create', as: :inviteF

end

app/views/shared/_footer.html.erb
<footer id="footer" class="border-top-0 bg-color-secondary mb-0">
        <div class="container">
            <div class="row py-5">
                <div class="col text-center">
                    <ul class="footer-social-icons social-icons social-icons-clean social-icons-big social-icons-opacity-light social-icons-icon-light mt-1">
                        <li class="social-icons-facebook"><a href="http://www.facebook.com/" target="_blank" title="Facebook"><i class="fab fa-facebook-f"></i></a></li>
                        <li class="social-icons-twitter"><a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fab fa-twitter"></i></a></li>
                        <li class="social-icons-linkedin"><a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fab fa-linkedin-in"></i></a></li>
                    </ul>
					<ul class="footer-social-icons social-icons social-icons-clean social-icons-big social-icons-opacity-light social-icons-icon-light mt-1">
						<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-dot-circle text-color-primary top-1 p-relative"></i>
                            <a href="/home/contact" class="text-color-light opacity-7 pl-1">CONTACTO</a></span>
						<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-dot-circle text-color-primary top-1 p-relative"></i>
                            <a href="/home/terms_of_use" class="text-color-light opacity-7 pl-1">CONDICIONES DE USO</a></span>
						<span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-dot-circle text-color-primary top-1 p-relative"></i>
                            <a href="/home/program_of_yumis" class="text-color-light opacity-7 pl-1">PROGRAMA DE YUMIS</a></span>
					</ul>                    
                </div>
            </div>
        </div>
        <div class="footer-copyright footer-copyright-style-2 bg-color-secondary">
            <div class="container py-2">
                <div class="row py-4">
                    <div class="col-lg-8 text-center text-lg-left mb-2 mb-lg-0">
                        <p>
                            <span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="fas fa-map-marked-alt text-color-primary top-1 p-relative"></i><span class="text-color-light opacity-7 pl-1">Final Av. Teherán, Urb. Montalbán, Caracas, Venezuela </span></span>
                            <span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="fab fa-whatsapp text-color-primary top-1 p-relative"></i><a href="tel:1234567890" class="text-color-light opacity-7 pl-1">(+58) 407.4187 </a></span>
                            <span class="pr-0 pr-md-3 d-block d-md-inline-block"><i class="far fa-envelope text-color-primary top-1 p-relative"></i><a href="lapromoucab@gmail.com" class="text-color-light opacity-7 pl-1">lapromoucab@gmail.com</a></span>
                        </p>
                    </div>
                    <div class="col-lg-4 d-flex align-items-center justify-content-center justify-content-lg-end mb-4 mb-lg-0 pt-4 pt-lg-0">
                        <p class="text-color-light opacity-7">© 2019 JOSELITO UCAB. Todos los Derechos Reservados.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>

app/views/shared/_header.html.erb
<header id="header" class="header-effect-shrink " data-plugin-options="{'stickyEnabled': true, 'stickyEffect': 'shrink', 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyChangeLogo': true, 'stickyStartAt': 120, 'stickyHeaderContainerHeight': 70}">
        <div class="header-body border-top-0">
            <div class="header-top border-bottom-0 bg-color-secondary">
                <div class="container">
                    <div class="header-row py-2">
                        <div class="header-column justify-content-center justify-content-md-start">
                            <div class="header-row">
                                <nav class="header-nav-top">
                                    <ul class="nav nav-pills">
                                        <li class="nav-item">
                                            <span class="text-light opacity-30 pl-0">El mejor lugar para comer LAPROMO!</span>
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="header-column justify-content-end d-none d-md-flex">
                            <div class="header-row">
                                <nav class="header-nav-top">
                                    <ul class="nav nav-pills">
                                    
                                    <% if !user_signed_in? %>
                                        <li class="nav-item">
                                            <i class="far fa-user text-4 text-color-primary" style="top: 0;"></i> 
                                            <%= link_to  "Iniciar sesión", new_user_session_path, style: "color: White;" %>
                                        </li>
                                        <li class="nav-item">
                                            <i class="far fa-edit text-4 text-color-primary" style="top: 0;"></i> 
                                            <%= link_to  "Registrarse", new_user_registration_path, style: "color: White;" %>
                                        </li>  
                                    <% else %>
                                      <p  style="color: white; margin-top: 1%">Bienvenido, <%= current_user.user_name%></p>
                                        <i class="fas fa-user-circle text-4 text-color-primary" style="top: 0; padding: 8px;"></i>
                                            <li class="dropdown" >
                                                <button class=" dropbtn">Mi Cuenta</button>   
                                                    <ul class="dropdown-content ">
                                                        <!-- AQUI VA LOS AJUSTE DEL USUARIO -->
                                                        <li><%= link_to "Datos de acceso", edit_user_registration_path, style:'text-decoration:none;' %></li>
                                                        <!-- AQUI VA LOS YUMIS DEL USUARIO -->
                                                        <li><%= link_to "Datos personales",comensal_editar_path, style:'text-decoration:none;'%></li>

                                                        <!-- AQUI VAN LOS YUMIS DEL USUARIO  -->
                                                        <li><%= link_to "Mis Yumis",comensal_yumis_path, style:'text-decoration:none;'%></li>
                                                        <!-- AQUI VA EL LA RESERVAS DEL USUARIO  -->                                                        
                                                        <li><%= link_to "Mis reservas",reservations_index_path, style:'text-decoration:none;'%></li>
                                                        <!-- AQUI VA LOS COMENTARIOS DEL USUARIO  -->
                                                        <li><%= link_to "Mis comentarios", my_comments_path, style:'text-decoration:none;'%></li>
                                                        <!-- AQUI VA LOS FAVORITOS DEL USUARIO  -->
                                                        <li><%= link_to "Mis favoritos",'', style:'text-decoration:none;'%></li>
                                                        <!-- AQUI VA EL MANEJO DE SUBSCRIPCONES  -->
                                                        <li><%= link_to "Mis Subscripciones de email", :diner_subscriptions, style:'text-decoration:none;'%></li>
                                                    </ul>  
                                            </li>
                                        
                                        <li class="nav-item">
                                            <i class="fa fa-sign-in-alt  text-4 text-color-primary" style="top: 0;"></i> 
                                            <%= link_to  "Cerrar sesión", destroy_user_session_path, method: :delete, style: "color: White;" %>
                                        </li>                                          
                                    <% end %>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-wrapper" style="min-height: 100px;">
            <div id="wrap" class="header-container container-fluid">
                <div class="header-row">
                    <div class="header-column">
                        <div class="header-row">
                            <div class="header-logo">
                                <%= link_to '/home/index',style:"text-decoration:none" do %>
                                    <%= image_tag '/assets/logo-lapromo-9761a68b1de5779d036107e446ed0488090657142af07104d6a135a853adb41a.jpg', width: 200, height: 60 %>
                                <%end%>
                            </div>
                        </div>
                    </div>
                    <div class="header-column justify-content-end">
                        <div class="header-row">
                            <div class="header-nav order-2 order-lg-1">
                                <div class="header-nav-main header-nav-main-effect-1 header-nav-main-sub-effect-1">
                                    <nav class="collapse">
                                        <ul class="nav nav-pills" id="mainNav">
                                            <li>
                                            <!-- AQUI VA LA DIRECCION DEL HOME  -->
                                                <%= link_to '/home/index' , style:"text-decoration:none" do %>
                                                    HOME
                                               <%end%>
                                            </li>
                                            <li>
                                                <!-- AQUI VA LA DIRECCION DEL BUSCADOR -->
                                                <%= link_to restaurants_buscador_path, style:"text-decoration:none",data: {turbolinks: false} do  %>
                                                    BUSCADOR
                                                 <%end%>
                                            </li>
                                         
                                            <li>
                                                <!-- AQUI VA LA DIRECCION PARA PREGUNTAS FRECUENTES -->
                                                 <%= link_to topics_index_path, style:"text-decoration:none" do %>
                                                    PREGUNTAS FRECUENTES
                                                <%end%>
                                            </li>
                                            <li>
                                                <!-- AQUI VA LA DIRECCION PARA PROGRAMA YUMIS -->
                                                <%= link_to '/home/program_of_yumis', style:"text-decoration:none" do %>
                                                    PROGRAMA YUMIS
                                                <%end%>
                                            </li>
                                            <li>
                                                <!-- AQUI VA LA DIRECCION PARA GUIA RAPIDA DE USUARIO -->
                                                <%= link_to '/home/quick_user_guide', style:"text-decoration:none" do %>
                                                    GUIA RAPIDA
                                                <%end%>

                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main nav">
                                    <i class="fas fa-bars"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </header>
    <script>
   // Llama a la funcion al scrollear
window.onscroll = function() {myFunction()};
var navbar = document.getElementById("wrap");
// Recibe la posicion offset del navbar
var sticky = navbar.offsetTop;
function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
    </script>

app/views/shared/_registro_restaurant.erb
<div class="container">
    <div class="py-5">
			<section class=" section-1 text-align: center ">

			<!-- AQUI VA LA DIRECCION DE REGISTRO DEL RESTAURANTE  -->
            <a style="text-decoration:none" href="  ">       
			<div class="parallax-settings parallax-bg-5">	
				<div class="thumb-info-wrapper m-0 container2 height-child" >
					
						<div class="row my-4 height-child">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="py-3 mb-3 text-center text-color-light" style="font-size:40px"><strong> ¿ Eres dueño de un restaurante ? </strong></h1> 
								<h1 class="py-3 mb-3 text-center text-color-light " style="font-size:24px" >	Únete a La PROMO y aumenta tu visión online con nosotros y atrae a nuevos clientes</h1>
							</div>
						</div>
					</div>
				</div>
				</div>
			</a>
		</section>
    </div>
</div>