config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/empty'
  get 'articles/index'
  get '/articles/:id/contenido', to: 'articles#contenido', as: 'contenido'
  get 'articles/empty'
  get 'articles/busqueda'
  get 'places/index'
  get 'places/empty'
  get 'restaurants/buscar_x_estado/muestra', to: 'restaurants#buscar_x_estado', as: 'muestra'
  get 'restaurants/buscar_x_tipo_comida/mostrar', to: 'restaurants#buscar_x_tipo_comida', as: 'mostrar'
  get 'restaurants/mapa'
  get 'restaurants/avanzada'
  get 'restaurants/buscar_x_tipo_promo/promo', to: 'restaurants#buscar_x_tipo_promo', as: 'promo'
  get 'home/index'
  get 'home/program_of_yumis'
  get 'home/quick_user_guide'
  get 'home/terms_of_use'
  get 'home/contact'
  get 'restaurants/calification-filter'
  get 'restaurants/buscador'

  root 'home#index'

  get 'reservations/index', to: 'reservations#index', as: :reservations_index
  get 'reservations/cancelar/:id', to: 'reservations#cancelar', as: :reservations_cancelar
  put 'reservations/cancelar/:id', to: 'reservations#actualizando_cancel', as: :actualizando_cancel

  namespace :administrador do
    get 'home', to: 'home#index'
    get '', to: 'home#index'
    resources :restaurants
    put 'approved/:id', to: 'restaurants#approve_restaurant', as: :approve
    get 'aprobados', to: 'restaurants#approved_restaurants', as: :aprobados
    get 'aprobados/:id', to: 'restaurants#cancel_restaurant', as: :cancel
    delete 'rechazar/:id', to: 'restaurants#reject_restaurant', as: :reject_restaurant
    get 'not_approved', to: 'restaurants#not_approved_restaurants', as: :not_approved
    resources :articles
    get '/articles/:id/confirm', to: 'articles#confirm', as: 'confirm'
    get :warning_diners, to: 'no_shows#warning_diners', as: :warning_diners
    get :should_block, to: 'no_shows#should_diner_block', as: :should_diners
    get 'should_block/:id', to: 'no_shows#block_diner', as: :block_diners
    get :blocked_diners, to: 'no_shows#blocked_diners', as: :blocked_diners
    get 'blocked_diners/:id', to: 'no_shows#unblock_diners', as: :unblock_diners
    get 'warning_diners/:id', to: 'no_shows#warn_diner', as: :warn_diners
    get :gift_diners, to: 'no_shows#gift_diner', as: :gift_diners
    get 'gift_diners/:id', to: 'no_shows#giving_yumis', as: :give_yumis
  end

  namespace :restaurante do
    get 'home', to: 'home#index'
    get 'editar', to: 'restaurants#edit'
    patch 'editar', to: 'restaurants#update', as: :restaurant
    put 'editar', to: 'restaurants#update', as: nil
    post 'borrar_photo', to: 'restaurants#destroy_photo'
    get 'display_reservations', to: 'reservations#display_reservations', as: 'reservas'
    get 'display_res_date', to: 'reservations#display_res_date', as: 'por_fecha'
    get 'show1', to: 'reservations#show1', as: 'show1'
    get 'show2', to: 'reservations#show2', as: 'show2'
    get 'cancelar-reservas', to: 'restaurants#reservation'
    get 'get-reservas', to: 'restaurants#get_reservation'
    patch 'cancelar-reserva', to: 'restaurants#cancel_reservation', as: :cancel_reserva
    resources :menu_types
    resources :promos
    resources :calendars
    resources :plates
    resources :reservations
    get '/reservations', to: 'reservations#index'
    put '/reservations/:id/update_status', to: 'reservations#update_status'
  end
  #Ruta para info de restaurante
  get 'restaurant_info/:restaurantID', to: 'restaurants#restaurant_info', as: :restaurant_info
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users, skip: :registrations, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords' }
  devise_scope :user do
    get '/users', to: redirect('/users/sign_up')
    get '/users/password', to: 'users/passwords#new'
    get '/users/sign_out', to: 'users/sessions#destroy'
    get '/users/restaurant/sign_up', to: 'users/registrations#create_restaurant'
    post '/users/restaurant/sign_up', to: 'users/registrations#create'
    get 'usuario/editar', to: 'users/registrations#edit', as: :edit_user_registration
    put 'usuario/editar', to: 'users/registrations#update', as: nil
    patch 'usuario/editar', to: 'users/registrations#update', as: :user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/sign_up', to: 'users/registrations#new', as: :new_user_registration
    delete '/users', to: 'users/registrations#destroy', as: nil
    post '/users', to: 'users/registrations#create', as: nil
  end
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurant, only: [:index, :show]
  get '/diner-subscriptions', to: 'diner_subscriptions#index'
  patch '/diner-subscriptions', to: 'diner_subscriptions#update'
  namespace 'api', defaults:{format:"json"} do
    namespace 'v1' do
      #Inicio Grupo 4 rutas
        devise_for :users
        #Lista de lugares
        get 'place_list', to: 'places#place_list'
        #Lista de restaurantes por estado
        get 'restaurant_list/:id', to: 'restaurants#restaurant_list'
        #LIsta de restaurantes por tipo de comida
        get 'restaurant_name', to: 'restaurants#restaurant_name'
        get 'restaurant_address', to: 'restaurants#restaurant_address'
        get 'restaurant_kitchen_type', to: 'restaurants#restaurant_kitchen_type'
        get 'restaurant_search/:id', to: 'restaurants#restaurant_search'
        #Lista de tipo de comida
        get 'kitchen_type_list', to:'kitchen_type#kitchen_type_list'
        get 'promo_type_list/:id', to:'promos#promo_type_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'
        get 'promo_restaurant/:id', to:'promos#promo_restaurant'
        get 'promo_dates_list/:id/:rest_id', to:'promos#promo_dates_list'
        get 'promo_detail_list', to:'promos#promo_detail_list'

        post 'api_invitation', to:'api_invitation#api_invitation'
        post 'api_reservation', to:'api_invitation#api_reservation'
        get 'api_reservation/:id/1478965', to:'api_invitation#api_reserve_cancel'
        get 'api_reserve_invitation_yumies/:user_id/1478965', to:'api_invitation#api_reserve_invitation_yumies'
      #FIn Grupo 4 rutas
      # -------------------------------------------
      # Rutas de la seccion de preguntas frecuentes
      # -------------------------------------------
      get 'temas', to: 'articles#temas' # Retorna el listado de temas
      get 'articulos', to: 'articles#articulos' # Retorna el listado de articulos
      get 'art_per_tema/:id', to: 'articles#art_per_tema' # Retorna los articulos que pertenecen al tema especificado
      get 'add_tendencia/:id', to: 'articles#add_tendencia' # Aumenta la tendencia de un articulo al clickearlo
      # ------------------------------------------------
      # Rutas de la seccion de información de restaurant
      # ------------------------------------------------
      get 'restaurant_info/:id', to: 'restaurants#restaurant_info'# Retorna la info de un restaurant
      # ------------------------------------------
      # Rutas de la seccion de realizacion reserva
      # ------------------------------------------
      get 'reserva/:id', to: 'reservations#reserva' # Retorna las fechas del calendario junto a las promos
      # -------------------------------------------------
      # Ruta para retornar notificaciones de calificación
      # -------------------------------------------------
      get 'notificacion/calificacion_pend/:id', to: 'comments#pending_comment'
      get 'calificar/:id', to: 'comments#get_info'
      post 'calificar', to: 'comments#registrar_comment'
      post 'invitar_registro', to: 'invites#invitar'
    end
  end
  # Rutas para comensal
  namespace :comensal do
    get :editar, to: 'diners#edit'
    ## RUTAS PARA MIS YUMIS
    get :yumis, to: 'hist_yumis#mis_yumis'
    get :yumis_amigos, to: 'hist_yumis#yumis_amigos'
    get :yumis_reservas_efect, to: 'hist_yumis#yumis_reservas_efectuadas'
    get :yumis_reservas_noefect, to: 'hist_yumis#yumis_reservas_noefectuadas'
    get :yumis_reservas_canceladas, to: 'hist_yumis#yumis_reservas_canceladas'
    #####################################
    patch :editar, to: 'diners#update', as: :diner
    post :editar, to: 'diners#update', as: :diners
  end
  # rutas para obtener estado municipio y parroquia de lugar
  get 'get_estados', to: 'places#get_states'
  get 'get_municipios', to: 'places#get_municipios'
  get 'get_parroquias', to: 'places#get_parroquias'

  # Filtros para buscar restaurantes por calificaciones
  get 'restaurants-calification', to: 'restaurants#calification_filter'
  get 'buscador', to: 'restaurants#buscador'
  #bucar restaurantes por promociones activas
  # get 'restaurants-promos', to: 'restaurants#promos_date_filter'
  get 'restaurants-yummys', to: 'restaurants#yummys_filter'

  #Rutas para comentarios y Opiniones
  get 'ShowOpinion/:restaurantID', to: 'comments#ShowOpinion' , as: :my_link
  get 'my_comments', to: 'comments#my_comments'

  # rutas para crear los comentarios de las reservaciones
  get '/reservations/:id/comment', to: 'reservation_comment#new', as: 'reservation_comment'
  post '/reservations/:id/comment', to: 'reservation_comment#create'
  
  # ruta para crear reservas
  post '/reservation/:restID', to: 'reservations#create', as: :reservation_create

   #Post para invitar amigos a la reserva 
   post 'inviteF/:restID', to: 'invitations#create', as: :inviteF

end

app/controllers/administrador/home_controller.rb
class Administrador::HomeController < ApplicationController
  before_action :authenticate_admin!
  layout 'administrador'
  def index
    @restaurant = Restaurant.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :set_redirect

  def index
   
  	@places = Place.restaurantes.order(:name).page(params[:page]).per_page(6)
    #@places = Place.where(type_place: 'estado').page(params[:page]).per_page(6)
	if @places.empty? 
		flash[:warning2] = "Actualmente no existen proveedores de servicio registrados"
		render :empty
	elsif ((@places.count == 1) and (@places.pluck('id')[0] ==  25))
		redirect_to muestra_path(place_id: @places[0].id)
	end

	#Para la muestra de los restaurantes con mas reservas, limitado a 8 restaurantes
   	#@restaurants = Restaurant.all #esta linea se uso para probar la conexion entre controlador y base de datos
    @restaurants = Restaurant.mas_reservados.limit(9)
    if @restaurants.empty?
        flash.now[:warning] = "No hay reservaciones registradas en ningun restaurant"
        #render :empty_search
    end

  #Se utiliza para traer al index todos los tipos de cocinas guardados en la BD
    #asegurandose de que no se repita el nombre de los tipos de comida
    @kitchens = KitchenType.select(:name).distinct.order(:name).all
    if @kitchens.empty? 
      flash.now[:warning] = "No se han registrado tipos de cocina en la aplicacion"
      #render :empty_search
    end    

  
  #Se utiliza para traer al index todos los tipos de promociones guardados en la BD
    #asegurandose de que no se repita el nombre de los tipos de promocion
    @promos = Promo.select(:promo_type).distinct.order(:promo_type).all
    if @promos.empty? 
      flash.now[:warning] = "No se han registrado tipos de promocion en la aplicacion"
      #render :empty_search
    end  
  end
    

  def empty

  end

  def contact
  end

  def terms_of_use
  end

  def program_of_yumis
  end

  def quick_user_guide
  end

  def empty_search

  end
  def set_redirect
    if user_signed_in? && current_user.is_admin?
      redirect_to administrador_home_path
    elsif user_signed_in? && current_user.is_restaurant?
      redirect_to restaurante_home_path
    end	
  end
  
  

end

app/controllers/restaurante/home_controller.rb
class Restaurante::HomeController < ApplicationController
  layout 'restaurante'
  before_action :authenticate_restaurant!
  def index; end
end

app/helpers/administrador/home_helper.rb
module Administrador::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_buscador_restaurantes.html.erb
<br>
<h3 style="margin-left: 85px; text-transform: capitalize"> 
  Buscar restaurantes <strong style="color: #e09b23"> por Tipo De Comida</strong></h3>
<div class="container" style="padding-left: 24px;">
    <% @kitchens.each do |k| %>
      <%= link_to k.name, mostrar_path(name: k.name), 
        :class => "btn btn-default btn-flat", :style => "color: #e09b23" %>
    <% end %>
</div>
<br>

app/views/home/_buscador_restaurantes_promo.html.erb
<br>
<h3 style="margin-left: 85px; text-transform: capitalize"> 
  Buscar restaurantes <strong style="color: #e09b23"> por Tipo De Promoción</strong></h3>
<div class="container" style="padding-left: 24px;">
    <% @promos.each do |k| %>
      <%= link_to k.promo_type, promo_path(promo_type: k.promo_type), 
         :class => "btn btn-default btn-flat" , :style => "color: #e09b23" %>
    <% end %>
</div>
<br>

app/views/home/_estados.html.erb
<div class="container">

					<div class="row mb-4">
					
								<% @places.each do |place| %>

						<div class="col-md-6 col-lg-4 p-3 isotope-item">
							
							<div class="listing-item" >
								<%= link_to muestra_path(place_id: place.id) do %>
									<div class="thumb-info thumb-info-lighten border">
										
										<div class="thumb-info-wrapper m-0 container2" >
											
													
													<%a = Photo.estados(place.id)%>

													<%= image_tag a[0] ,style: "filter: brightness(60%);"%>
														<div class="centered">
															<h2 style = "word-spacing: 999999999999999999px; font-size:50px; color: white">
																<%=place.name%></h2>
														</div>
																							
										</div>

										
									</div>
									<%end%>
									<div class="thumb-info-price bg-color-primary text-color-light text-4 pl-4 ">
											<p style="color:white; font-size: 10px;">Cantidad de Restaurantes: <%=Restaurant.places(place.id)%></p>
									
									</div>
								
							</div>
							
						</div>
						
<%end%>

							
							
					</div>
					
				<%= will_paginate @places, class: "digg_pagination pagination justify-content-center", previous_label: "<", next_label: ">"%>
				<br>
				
	</div>


				

app/views/home/_mas_reservado.html.erb
<div class="container">
<br>
<br>
<h2> Restaurantes <strong style="color: #e09b23">más </strong> Reservados</h2>
	<div class="row mb-4">
		<% @restaurants.each do |restaurant| %>
			<div class="col-md-4 col-lg-4 col-xs-6 p-3 isotope-item">
				<div class="listing-item thumb-info-wrapper" >
					<div class="thumb-info thumb-info-lighten border" style="border: none !important;">
					<!-- Para redirigirse a la información del restaurant-->
					<%= link_to restaurant_info_path(restaurantID:restaurant.id) do%>
					<!-- Aqui se obtiene la imagen del scope Photo  -->
						<div class="thumb-info-wrapper m-0 container2" >
							
							<div class = "img-fluid mx-auto"  style: "display: block; overflow: hidden; ">
								<%photo_restaurant=Photo.photo_restaurant(restaurant.id) %>
								<% if photo_restaurant[0] %>
									<%= image_tag photo_restaurant[0], style: "filter: brightness(60%);  max-height: 290px;" %>
								<% else %>
									<%= image_tag "https://live.staticflickr.com/65535/49191292228_e3b7a20bbd_o.png" %>
								<% end %>
							</div>
						</div>
					</div>
					<section class=" bg-color-primary text-color-light p-3 " style="margin-top: 5px;">
					<!-- Se muestran los datos obtenidos en una lista -->
						<h2 style = "word-spacing: 2px; text-transform: capitalize; font-size:30px; color:white; text-align: center; padding-bottom: 0px;">
							<%=restaurant.name %></h2>
						<ul style = "font-size:12px;color:white">
							<li>Total Reservas: <%= restaurant.total_reservas %></li>
							<!-- Aqui se obtiene la informacion del promedio a traves de los scope Plate y Comment y con.round se redondea el valor a 2 decimales  -->
							<% if Plate.avg_price_rest(restaurant.id).is_a? Numeric%>
								<li>Precio plato promedio: <%= Plate.avg_price_rest(restaurant.id).round(2)%> $</li>
							<% else %>
								<li>Precio plato promedio:"No hay promedio disponible"</li>
							<% end %>
							<% if Comment.avg_kitchen_score_rest(restaurant.id).is_a? Numeric%>
								<li>Puntuacion promedio(cocina): <%= Comment.avg_kitchen_score_rest(restaurant.id).round(2)%>/5</li>
							<% else %>
								<li>Puntuacion promedio(cocina): "No hay puntuacion disponible"</li>
							<% end %>
							<li>Descripción: <%= restaurant.description %></li>
							<li>Dirección: <%=restaurant.address %></li>
						</ul> 
					</section>
				</div>
			</div>
			<%end%>
		<%end%>
	</div>
	
</div> 

app/views/home/_registro_restaurant.erb
<div class="container">
    <div class="py-5">
			<section class=" section-1 text-align: center " style="text-decoration:none" >

			<!-- AQUI VA LA DIRECCION DE REGISTRO DEL RESTAURANTE  -->
            <%= link_to users_restaurant_sign_up_path, style:"text-decoration:none" do %>

			<div class="parallax-settings parallax-bg-5">	
				<div class="thumb-info-wrapper m-0 container2 height-child" >
					
						<div class="row my-4 height-child">
							<div class="col-md-12 align-self-center p-static order-2 text-center">
								<h1 class="py-3 mb-3 text-center text-color-light" style="font-size:40px"><strong> ¿Eres dueño de un restaurante? </strong></h1> 
								<h1 class="py-3 mb-3 text-center text-color-light " style="font-size:24px" >	Únete a LAPROMO, aumenta tu visibilidad online y atrae a nuevos clientes</h1>
							</div>
						</div>
					</div>
				</div>
				</div>
			<%end%>
		</section>
		<div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <%= link_to new_user_registration_path, style:"text-decoration:none"  do %>
                            <div class=" card2 fondo-1">
                                <div class="centered centered2">
                                <p class="  text-color-light" style="text-align: center;"><strong>¡Únete a <br>LAPROMO!</p></strong>
                                </div>
                            </div>
                        <%end%>
                    </div>

                    <div class="col-sm-8">
                        <%= link_to'/home/program_of_yumis', style:"text-decoration:none" do%>
                            <div class="card2 yumi" style="margin-right: 100px">
                                    <div  style="padding-right: 10px">
                                        <div>  
                                        <h2 class="text-100  text-color-light"> <strong>Premiamos tu confianza</strong> </h2> 
                                        <h5 style="text-transform: none;color:white" > Cuanto más reservas, más ganas:<br><br>
                                            1.000 Yumis = paga 400.000 Bs menos en tu próxima reserva en los restaurantes participantes.<br><br>
                                            2.000 Yumis = 1.000.000 Bs. </h5> 
                                            <p style="text-align: right; color:white"><strong>Descubre el programa Yumis</strong></p>
                                        </div>
                                        
                                    </div>
                            </div>
                        <%end%>
                    </div>
	</div>

app/views/home/contact.html.erb
<div class="body">
	<div role="main" class="main">
		<section class=" section-1">
			<div class="parallax-settings parallax-bg-4">
				<div class="thumb-info-wrapper m-0 container2 height-child" >
					<div class="container height-child">
						<div class="row my-4 height-child">
							<div class="col-md-12 align-self-center p-static order-2 text-center" style="margin-top: 120.1px;">
								<h1 class="text-100 py-4 mb-3 text-center text-color-light"><strong>¡Nos encantará poder ayudarte!</strong></h1>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>


		<section class="section-4">
			<!-- LIBRERIA Y LINK NECESARIO PARA FUNCIONAMIENTO DEL CARRUSEL -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
			<!-- LIBRERIA Y LINK NECESARIO PARA FUNCIONAMIENTO DEL CARRUSEL -->
			
			<h3 class="text-center text-success mt-4 mb-2"><strong>Las preguntas más frecuentes</strong></h3>
				<div class="container">
					<div class="accordion" id="accordionExample">
						
						<div class="card z-depth-0 bordered">
							<button class="btn btn-link btn-primary btn-custom-size" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne" style="text-decoration:none; background-color:#e09b23">
								<div class="card-header" id="headingOne">
									<h4 class="mb-0 btn-primary">
										¿Cómo puedo modificar mi cuenta?
									</h4>
								</div>
							</button>
							<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
								<div class="card-body">
									Podrás realizar estás modificaciones haciendo click en Iniciar Sesion, introduciendo tu email, password y seleccionando la opción Mis datos personales.<br>			
								</div>
							</div>
						</div>
						
						<div class="card z-depth-0 bordered">
							<button class="btn btn-link btn-primary btn-custom-size collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo" style="text-decoration:none; background-color:#e09b23">
								<div class="card-header" id="headingTwo">
									<h4 class="mb-0 btn-primary">
										¿Cómo puedo cancelar mi reserva?
									</h4>
								</div>
							</button>
							<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
								<div class="card-body">
									Puedes cancelar tu reserva accediendo a Mis Reservas en tu cuenta. <br>
								</div>
							</div>
						</div>
						
						<div class="card z-depth-0 bordered">
							<button class="btn btn-link btn-primary btn-custom-size collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree" style="text-decoration:none; background-color:#e09b23">
								<div class="card-header" id="headingThree">
									<h4 class="mb-0 btn-primary">
										¿Cómo puedo modificar mi reserva?<br>
									</h4>
								</div>
							</button>
							<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
								<div class="card-body">
									
									Comprueba en la página del restaurante que sigue teniendo disponibilidad. Cancela la reserva que quieres modificar y realiza una nueva.
								</div>
							</div>
						</div>
						
						<div class="card z-depth-0 bordered">
							<button class="btn btn-link btn-primary btn-custom-size collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour"  style="text-decoration:none; background-color:#e09b23">
								<div class="card-header" id="headingFour">
									<h4 class="mb-0 btn-primary">
										¿Hasta cuándo puedo dejar mi opinión después de mi reserva?
									</h4>
								</div>
							</button>
								<div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
									<div class="card-body">
										Tienes hasta 3 meses desde la fecha de tu reserva para dejar tu opinión. <br>
										De todas formas, te recomendamos dejar tu opinion lo antes posibles para que nos puedas detallar al máximo tu experiencia. <br>
									</div>
								</div>
						</div>

					
					</div>
				</div>
		</section>
			
			
		
		<section class=" section-9">
			<div class="container">
				<div>
					<div class="Contacto">
						<h2 class="Contacto-title">¡TE ESCUCHAMOS!</h2>
						<div class="Contacto-textContainer">
							<h4>¿Dudas adicionales?</h4>
							<p><b>¿Ya eres cliente?</b><br>

									<!-- AQUI VA LA DIRECCION DE REGISTRO DE USUARIO  -->
								- Contáctanos a través de  <a href="                " target="_blank" style="text-decoration:none">lapromoucab@gmail.com</a>
								<br>

								 			<!-- AQUI VA LA DIRECCION DE MOSTRAR PREGUNTA FRECUENTE  -->
								- O accede a nuestras <%=link_to "Preguntas frecuentes", topics_index_path, style:'text-decoration:none;'%>.<br><br>
							<b>¿Futuro cliente? </b><br><br>

											<!-- AQUI VA LA DIRECCION DE REGISTRO DE RESTURANTE  -->
								- Date de alta <%=link_to "aquí", new_user_session_path, style:'text-decoration:none' %> para tener acceso a todas las funcionalidades</p>

						</div>
					</div>
				</div>
			</div>	
		</section>

		<section class="container">
			<div class="row parallax-bg-6">
      			<div class="col-sm-6 textoc ">
				  	<h2 class="text-center" style="color:white"><strong> ¿Cómo puedes encontrarnos?</strong></h2><br>
					<h4 class="text-center " style="color:white">  Puedes contactar con nosotros de lunes a viernes desde las 9:00 A.M. hasta las 10:00 P.M.</h4> <br>
					<h4 class="text-center " style="color:white"> (+58) 407.4187 </h4> 
					<h4 class="text-center " style="color:white"> lapromoucab@gmail.com.com </h4><br>
					<h4 class="text-center " style="color:white">   Nuestra oficina está ubicada en: </h4> <br>
					<h4 class="text-center" style="color:white"> Final Av. Teherán, Urb. Montalbán, Caracas, Venezuela</h4> <br>
				</div>

      			<div class="col-sm-6" style="">
				  	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7846.92396388582!2d-66.9758!3d10.4642!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x43cb2d8100a63708!2sUniversidad%20Cat%C3%B3lica%20Andr%C3%A9s%20Bello!5e0!3m2!1ses-419!2sve!4v1575168423546!5m2!1ses-419!2sve" 
					width="580" height="460" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
				</div>
			</div>
		</section>	

		<section>
	  		<%= render  "registro_restaurant" %>	
		</section>

	</div>
</div>

app/views/home/empty.html.erb
        <!-- Begin page -->
        <div id="wrapper">
            <div class="content">
                      
                                <div class="text-center">
                                    <i class="h1 far fa-frown text-muted"></i> <i class=""></i>
                                    <h1 class="mb-3 orange" style ="color: #e09b23">Actualmente no existen proveedores de servicio registrados</h1>
                                    <p class="text-muted"> Lo sentimos, en este momento no contamos con  proveedores de 
                                    servicios registrados en nuestro sistema.<br>
                                    Intente nuevamente más tarde</p><br><br><br><br>
<br><br>
<br><br>




                                </div>
                            </div>
<section>
                            <%= render  "registro_restaurant" %>
                            </section>

                            
        </div>
        
        
        

app/views/home/empty_search.html.erb
<!-- Mensaje de error al no conseguir reservaciones de restaurantes -->
<head>
    <title>ERROR</title>
</head>

<body>
    <div class="content">
        <div style ="text-align: center;">
            <h2>No hay reservaciones registradas en ningun restaurant </h2>
        </div>
    </div>
</body>

app/views/home/index.js.erb
$("#products").html('<%=  escape_javascript(render :partial => 'estados') %>');
$('.pagination a').attr('data-remote', 'true');